-d C:\Gowin\gowin-blink\impl\synthesize\rev_1\fpga_project.vm
-cst C:\Gowin\gowin-blink\src\fpga_project.cst
-sdc C:\Gowin\gowin-blink\src\fpga_project.sdc
-p GW1N-4-LQFP144-6
-cfg C:\Gowin\gowin-blink\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-gpa
